Repository smallbusinesshero/storefront, pull requests merged in 2020-03, with the labels that each got.

#20 fix no search result not showing
  src/sites/home.js
Labels: bug

#21 Bugfix enter press
  src/sites/card-carousel.js
  src/sites/home.js
Labels: bug

#38 Feature/readme
  README.md
  logo.png
  preview.png
Labels: documentation

#36 Add license file
  LICENSE
Labels: documentation, frontend

#37 Frontend - CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
Labels: documentation, frontend
